# GG Bot Upload Assistant
# Copyright (C) 2022  Noob Master669

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# ********************************************** #
# ********************************************** #
#                GG-BOT Uploaders                #
# ********************************************** #
# ********************************************** #

# Image ID: noobmaster669/gg-bot-uploader:{TAG}
# Image Description: Normal Docker Image build and stored in Docker Registry
# Build Conditions: On all tags and master branch
dockerhub-gg-bot-upload-assistant:
  stage: deploy
  image:
    name: $DOCKER_IMAGE
  services:
    - name: docker:dind
      alias: buildcontainer
      entrypoint: ["dockerd-entrypoint.sh", "--tls=false"]
  variables:
    DOCKER_HOST: tcp://buildcontainer:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u "$DOCKER_CI_REGISTRY_USER" -p "$DOCKER_CI_REGISTRY_PASSWORD" $DOCKER_CI_REGISTRY
  script:
    - mv Dockerfiles/Dockerfile ./
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=":latest"
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      elif [[ $CI_COMMIT_TAG ]]; then
        tag=":$CI_COMMIT_TAG"
        echo "Running for tag '$CI_COMMIT_TAG': tag = $tag"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - |
      echo "Building Image '$DOCKER_CI_REGISTRY_IMAGE${tag}"
    - docker build --pull -t "$DOCKER_CI_REGISTRY_IMAGE${tag}" .
    - |
      echo "Publishing Image to Docker Hub Container Registry: '$DOCKER_CI_REGISTRY_IMAGE${tag}"
    - docker push "$DOCKER_CI_REGISTRY_IMAGE${tag}"
  rules:
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == "dev"' # runs for every tags and master branch and dev branch
      exists:
        - Dockerfiles/Dockerfile

dockerhub-gg-bot-upload-assistant-new:
  stage: deploy
  image:
    name: $DOCKER_IMAGE
  services:
    - name: docker:dind
      alias: buildcontainer
      entrypoint: ["dockerd-entrypoint.sh", "--tls=false"]
  variables:
    DOCKER_HOST: tcp://buildcontainer:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u "$DOCKER_CI_REGISTRY_USER" -p "$DOCKER_CI_REGISTRY_PASSWORD" $DOCKER_CI_REGISTRY
  script:
    - mv Dockerfiles/Dockerfile ./
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=":refactor-latest"
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'refactor-latest'"
      elif [[ $CI_COMMIT_TAG ]]; then
        tag=":refactor-$CI_COMMIT_TAG"
        echo "Running for tag '$CI_COMMIT_TAG': tag = $tag"
      else
        tag=":refactor-$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - |
      echo "Building Image '$DOCKER_CI_REGISTRY_IMAGE${tag}"
    - docker build --pull -t "$DOCKER_CI_REGISTRY_IMAGE${tag}" -f Dockerfile.new .
    - |
      echo "Publishing Image to Docker Hub Container Registry: '$DOCKER_CI_REGISTRY_IMAGE${tag}"
    - docker push "$DOCKER_CI_REGISTRY_IMAGE${tag}"
  rules:
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == "feature/auto_uploader"' # runs for every tags and master branch and dev branch
      exists:
        - Dockerfiles/Dockerfile.new


# Image ID: noobmaster669/gg-bot-uploader:aarch64-{TAG}
# Image Description: arm32v7 Docker Image build and stored in Docker Registry
# Build Conditions: On all tags and master branch
dockerhub-gg-bot-upload-assistant-aarch64:
  stage: deploy
  image:
    name: $DOCKER_IMAGE
  services:
    - name: docker:dind
      alias: buildcontainer
      entrypoint: ["dockerd-entrypoint.sh", "--tls=false"]
  variables:
    DOCKER_HOST: tcp://buildcontainer:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u "$DOCKER_CI_REGISTRY_USER" -p "$DOCKER_CI_REGISTRY_PASSWORD" $DOCKER_CI_REGISTRY
  script:
    - mv Dockerfiles/Dockerfile.aarch64 ./
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=":aarch64-latest"
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'aarch64-latest'"
      elif [[ $CI_COMMIT_TAG ]]; then
        tag=":aarch64-$CI_COMMIT_TAG"
        echo "Running for tag '$CI_COMMIT_TAG': tag = $tag"
      else
        tag=":aarch64-$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - |
      echo "Building Image '$DOCKER_CI_REGISTRY_IMAGE${tag}"
    - docker build --pull -t "$DOCKER_CI_REGISTRY_IMAGE${tag}" -f Dockerfile.aarch64 .
    - |
      echo "Publishing Image to Docker Hub Container Registry: '$DOCKER_CI_REGISTRY_IMAGE${tag}"
    - docker push "$DOCKER_CI_REGISTRY_IMAGE${tag}"
  rules:
    - if: "$CI_COMMIT_TAG || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH" # runs for every tags and master branch
      exists:
        - Dockerfiles/Dockerfile.aarch64

# Image ID: noobmaster669/gg-bot-uploader:arm32v7-{TAG}
# Image Description: arm32v7 Docker Image build and stored in Docker Registry
# Build Conditions: On all tags and master branch
dockerhub-gg-bot-upload-assistant-armhf:
  stage: deploy
  image:
    name: $DOCKER_IMAGE
  services:
    - name: docker:dind
      alias: buildcontainer
      entrypoint: ["dockerd-entrypoint.sh", "--tls=false"]
  variables:
    DOCKER_HOST: tcp://buildcontainer:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u "$DOCKER_CI_REGISTRY_USER" -p "$DOCKER_CI_REGISTRY_PASSWORD" $DOCKER_CI_REGISTRY
  script:
    - mv Dockerfiles/Dockerfile.armhf ./
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=":arm32v7-latest"
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'arm32v7-latest'"
      elif [[ $CI_COMMIT_TAG ]]; then
        tag=":arm32v7-$CI_COMMIT_TAG"
        echo "Running for tag '$CI_COMMIT_TAG': tag = $tag"
      else
        tag=":arm32v7-$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - |
      echo "Building Image '$DOCKER_CI_REGISTRY_IMAGE${tag}"
    - docker build --pull -t "$DOCKER_CI_REGISTRY_IMAGE${tag}" -f Dockerfile.armhf .
    - |
      echo "Publishing Image to Docker Hub Container Registry: '$DOCKER_CI_REGISTRY_IMAGE${tag}"
    - docker push "$DOCKER_CI_REGISTRY_IMAGE${tag}"
  rules:
    - if: "$CI_COMMIT_TAG || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH" # runs for every tags and master branch
      exists:
        - Dockerfiles/Dockerfile.armhf

# Image ID: noobmaster669/gg-bot-uploader:FullDisk-{TAG}
# Image Description: Normal Docker Image build and stored in Docker Registry
# Build Conditions: On all tags and master branch
dockerhub-gg-bot-upload-assistant-fulldisk:
  stage: deploy
  image:
    name: $DOCKER_IMAGE
  services:
    - name: docker:dind
      alias: buildcontainer
      entrypoint: ["dockerd-entrypoint.sh", "--tls=false"]
  variables:
    DOCKER_HOST: tcp://buildcontainer:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u "$DOCKER_CI_REGISTRY_USER" -p "$DOCKER_CI_REGISTRY_PASSWORD" $DOCKER_CI_REGISTRY
  script:
    - mv Dockerfiles/Dockerfile.disk ./
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=":FullDisk-latest"
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'FullDisk-latest'"
      elif [[ $CI_COMMIT_TAG ]]; then
        tag=":FullDisk-$CI_COMMIT_TAG"
        echo "Running for tag '$CI_COMMIT_TAG': tag = $tag"
      else
        tag=":FullDisk-$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - |
      echo "Building Image '$DOCKER_CI_REGISTRY_IMAGE${tag}"
    - docker build --pull -t "$DOCKER_CI_REGISTRY_IMAGE${tag}" -f Dockerfile.disk .
    - |
      echo "Publishing Image to Docker Hub Container Registry: '$DOCKER_CI_REGISTRY_IMAGE${tag}"
    - docker push "$DOCKER_CI_REGISTRY_IMAGE${tag}"
  rules:
    - if: "$CI_COMMIT_TAG || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH" # runs for every tags and master branch
      exists:
        - Dockerfiles/Dockerfile.disk
